environment:
  matrix:
    - nodejs_version: 8
      platform: x64
      msvs_toolset: 12
    - nodejs_version: 8
      platform: x86
      msvs_toolset: 12
    - nodejs_version: 10
      platform: x64
      msvs_toolset: 12
    - nodejs_version: 10
      platform: x86
      msvs_toolset: 12
    - nodejs_version: 12
      platform: x64
      msvs_toolset: 12
    - nodejs_version: 12
      platform: x86
      msvs_toolset: 12

os: Visual Studio 2015

# Install scripts. (runs after repo cloning)
install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:PLATFORM
  # install modules
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

# Don't actually build.
build: off
